### ISSUE TITLE
Can traffic scenes generated by LCTG  be transformed to OpenScenario format?

### ISSUE THREAD

**Issue by haiyangp** [Ariostgx/lctgen#1]
could i use the generation result to build one OpenScenario file?

**Comment by Ariostgx** [comment]
Sorry for the late reply! Yes, it is possible to do that. We just need to convert each agent's bbox state into OpenScenario's format.

**Comment by ayushmohod** [comment]
Can you share any code demo available for generating map vector outputs to OS2.0 format?
