### ISSUE TITLE
Data Processing and Error Handling on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by tnmk1701** [Ariostgx/lctgen#2]
After running the file process_all_data.py, I received the following results:

1) In PATH_B, there are files with the format pkl (for example: file: 5_346.pkl). Are the results I received correct? What are these files and what role do they play?
![image](https://github.com/Ariostgx/lctgen/assets/115914696/18ed2bc7-9fa0-4cfe-960b-3a1a0e63cc2c)

2) I received files 0.log, 1.log,..., 9.log. Among them, file 0.log has an error: 
![image](https://github.com/Ariostgx/lctgen/assets/115914696/3324d73e-0c3a-4c57-a918-238998baf940)
![image](https://github.com/Ariostgx/lctgen/assets/115914696/f02d495a-2b47-4030-a28e-3798c4044d51)

and the remaining files have the same error:
![image](https://github.com/Ariostgx/lctgen/assets/115914696/6b50942c-50e6-44a3-8f90-6774bbe67b58)

Is there any way to resolve this?

I'm using the Ubuntu 22.04.4 operating system and do not have a GPU (but I can install the CUDA toolkit if necessary).

Thank you for reading, and I look forward to your prompt response.

**Comment by Ariostgx** [comment]
Hi, thanks for trying out our model!

For your questions:
1. Yes. Each of these files represent a 5s snapshot from the original Waymo dataset. These files are processed by `trafficgen/utils/trans20.py` to collect all the required information we need to train our model. Essentially, it is the same with the demo data we provided in the README.

2. For the error you see, it seems an error to do with the load of `TFRecordDataset`. From the error it seems some of the `tfrecord` file you downloaded to `PATH_A` is not working. Can you try to run L406-L412 of `trafficgen/utils/trans20.py` to debug which `tfrecord` file is causing the error?

**Comment by tnmk1701** [comment]
Thanks for getting back to me. I appreciate your help and I'm eager to learn more about this topic. Thanks again!
